name: Java CI with Maven (manual)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          check-latest: true

      - name: Force Maven toolchain to JDK 21
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/toolchains.xml <<'XML'
          <?xml version="1.0" encoding="UTF-8"?>
          <toolchains xmlns="http://maven.apache.org/TOOLCHAINS/1.1.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/TOOLCHAINS/1.1.0 https://maven.apache.org/xsd/toolchains-1.1.0.xsd">
            <toolchain>
              <type>jdk</type>
              <provides>
                <version>21</version>
              </provides>
              <configuration>
                <jdkHome>${env.JAVA_HOME}</jdkHome>
              </configuration>
            </toolchain>
          </toolchains>
          XML
          java -version
          mvn -v

      - name: Build with Maven
        run: mvn -B -DskipTests=false clean verify

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=boardgame
            -Dsonar.projectName=Boardgame

      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Build Docker Image
        run: |
          docker build -t boardgame:${{ github.sha }} .

      - name: Trivy Image Scan (non-blocking)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: boardgame:${{ github.sha }}
          format: 'table'
          output: 'trivy-image-report.txt'
          exit-code: '0'
