name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest   # your runner must have Docker available

    steps:
      - uses: actions/checkout@v4

      # Use JDK 21 (project targets release 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          check-latest: true

      # Ensure Maven uses this JDK (toolchains)
      - name: Force Maven toolchain to JDK 21
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/toolchains.xml <<'XML'
          <?xml version="1.0" encoding="UTF-8"?>
          <toolchains xmlns="http://maven.apache.org/TOOLCHAINS/1.1.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/TOOLCHAINS/1.1.0 https://maven.apache.org/xsd/toolchains-1.1.0.xsd">
            <toolchain>
              <type>jdk</type>
              <provides>
                <version>21</version>
              </provides>
              <configuration>
                <jdkHome>${env.JAVA_HOME}</jdkHome>
              </configuration>
            </toolchain>
          </toolchains>
          XML
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          mvn -v

      - name: Build with Maven
        run: mvn -B -DskipTests=false clean verify

      # ----- Install Trivy on the self-hosted runner (CLI mode) -----
      # Skip if it's already installed on your runner; otherwise keep this.
      - name: Install Trivy (Ubuntu/Debian)
        run: |
          if ! command -v trivy >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
            sudo apt-get update -y
            sudo apt-get install -y trivy
          fi
          trivy --version

      - name: Trivy FS scan (non-blocking)
        run: |
          trivy fs --format table -o fs.html . || true

      # ----- Sonar (version-pinned actions) -----
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t adijaiswal/boardgame:latest .

      - name: Trivy Image Scan (non-blocking)
        run: |
          trivy image --format table -o trivy-image-report.html --exit-code 0 adijaiswal/boardgame:latest

   
